export enum MFA {
  SMS = "SMS",
  EMAIL = "EMAIL",
  TOTP = "TOTP",
  NONE = "NONE",
}

export enum Roles {
  SUPER_ADMIN = "SUPER_ADMIN",
  ADMIN = "ADMIN",
  STUDENT = "STUDENT",
  TEACHING_ASSISTANT = "TEACHING_ASSISTANT",
  COURSE_CREATOR = "COURSE_CREATOR",
}
